version: "3"

services:
  new_market_db:
    container_name: new_market_db
    image: postgres:13.4
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - new_marketnet
    restart: unless-stopped

  # JS unique escrow service
  new_escrow_unique:
    container_name: new_escrow_unique
    build:
      context: ./unique-marketplace-escrow
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - DB_URL=${POSTGRES_URL}
      - ADMIN_SEED=${ADMIN_SEED}
      - MATCHER_CONTRACT_ADDRESS=${MATCHER_CONTRACT_ADDRESS}
    networks:
      - new_marketnet
    depends_on:
      - "new_market_db"
    restart: unless-stopped

  new_escrow_kusama:
    container_name: new_escrow_kusama
    build:
      context: ./unique-marketplace-escrow-kusama
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - POSTGRES_URL=${POSTGRES_URL}
      - DB_URL=${POSTGRES_URL}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_SEED=${ADMIN_SEED}
    networks:
      - new_marketnet
    depends_on:
      - "new_market_db"
      - "new_escrow_unique"
    restart: unless-stopped

  new_market_backend:
    container_name: new_market_backend
    build:
      context: ./unique-marketplace-api
      dockerfile: ./Dockerfile
    expose:
      - 5000
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - POSTGRES_URL=${POSTGRES_URL}
      - DB_URL=${POSTGRES_URL}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - API_PORT=5000
    networks:
      - new_marketnet
    depends_on:
      - "new_market_db"
      - "new_escrow_unique"
    restart: unless-stopped
    #command: /bin/bash -c "while true; do sleep 2; df -h; done"

  new_market_frontend:
    container_name: new_market_frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    build:
      context: ./unique-marketplace
      dockerfile: ./build_scripts/Dockerfile
    env_file:
      - .env
    environment:
      - DNS_RESOLVER=127.0.0.1
      - PORT=3000
      - ENV_FILE=/usr/share/nginx/html/env.js
      - INDEX_FILE=/usr/share/nginx/html/index.html
      - PRODUCTION=true
    networks:
      - new_marketnet
    depends_on:
      - "new_market_backend"
    restart: unless-stopped

networks:
  new_marketnet:
    driver: bridge

volumes:
  postgres:
